# Generated by Django 3.2.23 on 2024-09-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=12, unique=True)),
                ('current_year', models.IntegerField()),
                ('checkInDate', models.CharField(max_length=20)),
                ('checkOutDate', models.CharField(max_length=20)),
                ('roomCount', models.IntegerField()),
                ('guestName', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=40)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('estimatedArrivalTime', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '酒店预约',
                'verbose_name_plural': '酒店预约',
                'db_table': 'hotels_order',
            },
        ),
    ]
