# Generated by Django 3.2.23 on 2024-09-13 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_order',
            name='selectedRoom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.roomtype'),
        ),
        migrations.AddField(
            model_name='hotel_order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
